# Generated by Django 5.0.4 on 2024-04-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0009_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default=20, max_length=100),
            preserve_default=False,
        ),
    ]
