# Generated by Django 5.0.4 on 2024-04-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0012_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_total',
        ),
        migrations.AddField(
            model_name='order',
            name='Orderplacedid',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
