# Generated by Django 5.0.4 on 2024-04-22 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0013_remove_order_product_total_order_orderplacedid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='my_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
