# Generated by Django 5.0.4 on 2024-04-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0015_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
