# Generated by Django 5.0.4 on 2024-05-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0017_order_payment_mode_order_upiid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='online_payment',
            field=models.BooleanField(default=False),
        ),
    ]
