# Generated by Django 5.0.4 on 2024-05-10 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0019_charge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charge',
            old_name='price',
            new_name='amount',
        ),
    ]
