# Generated by Django 5.0.4 on 2024-05-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0020_rename_price_charge_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='add_decimal',
            field=models.BooleanField(default=True),
        ),
    ]
